name: actions

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-django pytest-cov coverage

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


  verify-images:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull and verify images
      run: |
        docker pull tkazarin/foodgram-backend:latest
        docker pull tkazarin/foodgram-frontend:latest


  build-and-push:
    runs-on: ubuntu-latest
    needs: 
      - lint

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: |
          cd backend
          docker build . -t tkazarin/foodgram-backend:latest

      - name: Build frontend image
        run: |
          cd frontend
          docker build . -t tkazarin/foodgram-frontend:latest

      - name: Push backend image
        run: docker push tkazarin/foodgram-backend:latest

      - name: Push frontend image
        run: docker push tkazarin/foodgram-frontend:latest
